services:
  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker-1
    hostname: spark-worker-1
    environment:
      - SPARK_PUBLIC_DNS=192.168.1.102
      - SPARK_LOCAL_IP=0.0.0.0
    ports:
      - "8081:8081"
      - "7002:7002"
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://192.168.1.101:7077
      --cores 4 --memory 4G --webui-port 8081
    volumes:
      - ./:/opt/spark/data
    restart: unless-stopped